#!/usr/bin/env python3
##################################################################################
# Copyright (c) 2020, Kenneth P. J. Dyer <kenneth@avoceteditors.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of the copyright holder nor the name of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
##################################################################################

# Module Imports
import argparse
import pathlib
import sys

# Local Imports
import wulfila
import wulfila.config
import wulfila.log

if __name__ == '__main__':

    # Initialize Parser
    parser = argparse.ArgumentParser(
            prog="wulfila")

    ################## Options #################
    opts = parser.add_argument_group("Options")

    # Alternate Alphabet
    opts.add_argument("-a", "--alphabet", action="store_true",
        help="Displays terms using alternate alphabet," 
        + "(in cases where the language supports an alternate alphabet, such as Gothic).")

    # Debug
    opts.add_argument("-d", "--debug", action="store_true",
        help="Enables debugging messages to log output")

    # Force
    opts.add_argument("-f", "--force", action="store_true",
        help="Forces operations, (may overwrite existing data)")

    # Verbose
    opts.add_argument("-v", "--verbose", action="store_true",
        help="Enables verbosity in log output") 

    # Language Commnad
    parser.add_argument("--lang", default=None,
        help="Set language to reference")

    ################## COMMNADS #############################
    cmds = parser.add_subparsers(title="Commands")

    # Configuration Command
    conf_cmd = cmds.add_parser("config", help="Configures system to use Wulfila")
    conf_cmd.set_defaults(func=wulfila.config.run)

    # Version Command
    vers_cmd = cmds.add_parser("version", help="Reports version information")
    parser.set_defaults(func=wulfila.report_version)

    ###################  PARSE ARGS ##########################
    args = parser.parse_args()

    # Configure Logger
    wulfila.log.set_logger(args.verbose, args.debug)

    #################### RUN PROCESS #########################
    args.func(args)

    # Close
    sys.exit(0)



